[package]
authors = ["Atul Varma <varmaa@gmail.com>"]
edition = "2018"
name = "poker-fun"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33"
