[package]
authors = ["Atul Varma <varmaa@gmail.com>"]
edition = "2018"
name = "poker-fun"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1"
serde = {version = "1", features = ["derive"]}
